### ISSUE TITLE
Create a GitHub issue when an app is up for review

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter-dashboard#1]
## Problem

There are a few issues that we're currently facing with reviews:
* There's no way to be notified when an app is submitted for review
* Developers have no way to see the size of the review queue
* There's no good place for reviewers to have discussions about the review process

Plus some nice things would be:
* Being able to assign/request someone for a review

## Proposal

When an app is up for review, we should create a new issue with a link to the app's flatpak bundle

**Comment by danrabbit** [comment]
Old issue related to using PRs for this https://github.com/elementary/houston/issues/625

**Comment by btkostner** [comment]
This is now going to be handled with https://github.com/elementary/appcenter-reviews. PRs getting created can auto notify on slack and get more visibility now.
