### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by comradekingu** [elementary/appcenter-dashboard#54]
https://l10n.elementary.io/projects/appcenter/#information

Needs approval from translators.
I approve.

**Comment by lewisgoddard** [comment]
Repository seems to be under MIT: [`assets/package.json` Line 5](https://github.com/elementary/appcenter-dashboard/blob/master/assets/package.json#L5)

**Comment by comradekingu** [comment]
@lewisgoddard MIT into GPLv3 can be released, whereas GPLv3 doesn't go into MIT.
The translations are GPLv3-only for some reason, so translator agreement is required to get to GPLv3+, (or MIT for that matter).
