### ISSUE TITLE
AppCenter Dashboard fails and gives no information about nothing

### ISSUE THREAD

**Issue by JeysonFlores** [elementary/appcenter-dashboard#63]
Hello, I submitted an app in the AppCenter Dashboard. When I submit it, it fails automatically and the issue the bot opened on my app's repo gives no information about nothing. You can see it [here](https://github.com/JeysonFlores/hasher/issues/2)

![image](https://user-images.githubusercontent.com/68255757/130372745-be4ee82f-d922-4bce-8796-e3b0b97072c1.png)

What am I supposed to fix?

**Comment by btkostner** [comment]
This is actually from the houston repo, so your first issue was correct. The repository looks to be using flatpak, so the current developer.elementary.io (houston) will not work for it. The new dashboard is currently in development and not ready to use, but you can still submit your app for review by [opening a PR](https://github.com/elementary/appcenter-reviews#repository-structure) on [the appcenter-reviews](https://github.com/elementary/appcenter-reviews) repository.

**Comment by aral** [comment]
I just ran into this, several months after the release of elementary OS 6 (#84)

**Comment by btkostner** [comment]
We are aware of this. The new dashboard is not yet ready for prime time. In the mean time, you can follow the README on this repository to submit your application for elementary OS 6: https://github.com/elementary/appcenter-reviews
